#############################################################################
##
##  ToolsForFPGradedModules.gd   ToolsForFPGradedModules package
##                               Martin Bies
##
##  Copyright 2020      University of Oxford
##
#! @Chapter Tools for FPGradedModules
##
#############################################################################



####################################################################################
##
#! @Section Minimal free resolutions
##
####################################################################################

#! @Description
#! The argument is a list L of generators of an ideal and a homalg graded ring R.
#! This method then construct the left ideal in this ring generated by these generators.
#! @Returns a f.p. module presentation
#! @Arguments L, R
DeclareOperation( "LeftIdealForCAP",
                  [ IsList, IsHomalgGradedRing ] );

#! @Description
#! The argument is a list L of generators of an ideal and a homalg graded ring R.
#! This method then construct the right ideal in this ring generated by these generators.
#! @Returns a f.p. module presentation
#! @Arguments L, R
DeclareOperation( "RightIdealForCAP",
                  [ IsList, IsHomalgGradedRing ] );


####################################################################################
##
#! @Section Minimal free resolutions
##
####################################################################################

#! @Description
#! The argument is a graded left or right module presentation <A>M</A>.
#! We then compute a minimal free resolution of <A>M</A>.
#! @Returns a complex of projective graded module morphisms
#! @Arguments M
DeclareAttribute( "MinimalFreeResolutionForCAP",
                  IsFpGradedLeftOrRightModulesObject );

## for my convenience a method that displays all information about a (co)complex
DeclareOperation( "FullInformation",
                  [ IsCapComplex ] );

DeclareOperation( "FullInformation",
                  [ IsCapCocomplex ] );



####################################################################################
##
#! @Section Betti tables
##
####################################################################################

#! @Description
#! The argument is a graded left or right module presentation <A>M</A>.
#! We then compute the Betti table of <A>M</A>.
#! @Returns a list of lists
#! @Arguments M
DeclareAttribute( "BettiTableForCAP",
                  IsFpGradedLeftOrRightModulesObject );
